import { FormEvent, useCallback, useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, Clock3, ExternalLink, LocateFixed, Map, RefreshCw, Search, TrainFront } from "lucide-react";
import { Helmet } from "react-helmet-async";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import officialStations from "@/data/train-stations.json";

type Language="zh"|"en";
type Segment={Line?:string;Direction?:string;Stations?:string;FreePublicBus?:string;FreeMRTShuttle?:string};
type StatusData={normal:boolean;affectedSegments:Segment[];messages:string[];updatedAt:string};
type Station={name:string;address:string;codes:string[];lat:number;lng:number;distance?:number};
type Crowd={code:string;level:string};
const lines=[["NSL","南北线","North South Line","bg-red-600"],["EWL","东西线","East West Line","bg-green-600"],["NEL","东北线","North East Line","bg-purple-600"],["CCL","环线","Circle Line","bg-amber-500"],["DTL","滨海市区线","Downtown Line","bg-blue-600"],["TEL","汤申—东海岸线","Thomson-East Coast Line","bg-[#9a6b3f]"],["BPL","武吉班让轻轨","Bukit Panjang LRT","bg-slate-500"],["SKL","盛港轻轨","Sengkang LRT","bg-slate-500"],["PGL","榜鹅轻轨","Punggol LRT","bg-slate-500"]] as const;
const linePrefixes:Record<string,string[]>={NSL:["NS"],EWL:["EW","CG"],NEL:["NE"],CCL:["CC","CE"],DTL:["DT"],TEL:["TE"],BPL:["BP"],SKL:["SE","SW","STC"],PGL:["PE","PW","PTC"]};
const lineColours:Record<string,string>={NSL:"#dc2626",EWL:"#16a34a",NEL:"#9333ea",CCL:"#e5a20a",DTL:"#2563eb",TEL:"#9a6b3f",BPL:"#64748b",SKL:"#64748b",PGL:"#64748b"};
const officialMapUrls={en:"https://www.lta.gov.sg/content/dam/ltagov/getting_around/public_transport/rail_network/pdf/SM_EN_%28Ver210726%29_CCL6.pdf",zh:"https://www.lta.gov.sg/content/dam/ltagov/getting_around/public_transport/rail_network/pdf/SM_CH_%28Ver210726%29_CCL6.pdf"};
const officialStationList=officialStations as {code:string;en:string;zh:string}[];
const stationNameMap:Record<string,string>={...Object.fromEntries(officialStationList.map(station=>[station.code,station.zh])),DT36:"锡林",DT37:"双溪勿洛",TE23:"丹戎禺",TE24:"加东公园",TE25:"丹戎加东",TE26:"马林百列",TE27:"马林台",TE28:"实乞纳",TE29:"碧湾",TE30:"勿洛南",TE31:"双溪勿洛",CC30:"吉宝",CC31:"广东民",CC32:"爱德华太子路",CC33:"滨海湾",CC34:"海湾舫"};
const isLineCode=(code:string,prefix:string)=>(prefix==="STC"||prefix==="PTC")?code===prefix:new RegExp(`^${prefix}\\d+$`).test(code);
type LineBranch={prefixes:string[];anchor?:string;zh:string;en:string};
const branchesFor=(line:string):LineBranch[]=>line==="EWL"?[{prefixes:["EW"],zh:"东西线主线",en:"East West Line main route"},{prefixes:["CG"],anchor:"EW4",zh:"樟宜机场支线（由丹那美拉转乘）",en:"Changi Airport branch (transfer at Tanah Merah)"}]:line==="CCL"?[{prefixes:["CC"],zh:"环线主线",en:"Circle Line main route"},{prefixes:["CE"],anchor:"CC4",zh:"滨海湾支线（由宝门廊分出）",en:"Marina Bay branch (from Promenade)"}]:line==="SKL"?[{prefixes:["STC","SE"],zh:"盛港东环",en:"Sengkang East Loop"},{prefixes:["STC","SW"],zh:"盛港西环",en:"Sengkang West Loop"}]:line==="PGL"?[{prefixes:["PTC","PE"],zh:"榜鹅东环",en:"Punggol East Loop"},{prefixes:["PTC","PW"],zh:"榜鹅西环",en:"Punggol West Loop"}]:[{prefixes:linePrefixes[line]||[],zh:"全线车站",en:"All stations"}];
const copy={
zh:{brand:"忠邦华语演讲会温馨服务",heading:"查找附近地铁站",intro:"输入中文／英文站名或使用您的位置，并查看实时拥挤度与运行状态",bus:"巴士查询",mrt:"地铁查询",search:"输入地铁站名或站号",example:"例如：义顺、Yishun 或 NS13",go:"查询",location:"使用我的位置",locating:"正在查找最近地铁站…",results:"请选择地铁站",nearest:"距离最近的5个地铁站",metres:"米",noStation:"找不到相关地铁站，请尝试英文站名或车站编号。",locationError:"无法取得位置，请允许浏览器使用定位后重试。",crowd:"实时拥挤度",low:"人流较少",moderate:"人流适中",high:"人流较多",unavailable:"暂无拥挤度资料",selected:"已选择车站",normal:"所有地铁与轻轨服务正常",disruption:"部分路线服务受影响",normalHelp:"目前没有收到 LTA 发布的列车服务中断通知。",affected:"受影响路线",direction:"方向",stations:"受影响车站",publicBus:"免费公共巴士",shuttle:"免费地铁接驳",announcements:"乘客公告",lines:"路线状态",operating:"正常运行",affectedBadge:"服务受影响",refreshing:"正在读取 LTA 实时资料",error:"无法读取实时地铁资料",refresh:"刷新",updated:"更新时间",lineHelp:"点击路线查看全部车站",loadingLine:"正在读取车站…",mapTitle:"新加坡地铁总图",mapHelp:"预览陆交局地铁与轻轨路线图，可放大及左右移动查看。",previewMap:"预览新加坡地铁总图",openMap:"打开陆交局高清原图",close:"关闭",note:"资料来自新加坡陆路交通管理局 DataMall，每30秒自动更新。LTA目前不提供正常运行期间逐班列车的实时到站倒数。"},
en:{brand:"A warm service from Chong Pang TMC",heading:"Find a nearby MRT station",intro:"Search by station name or code, or use your location, then view live crowd and service status",bus:"Bus arrivals",mrt:"MRT search",search:"Enter station name or code",example:"For example: Yishun or NS13",go:"Search",location:"Use my location",locating:"Finding your nearest MRT stations…",results:"Choose a station",nearest:"5 nearest MRT stations",metres:"m",noStation:"No matching station found. Try an English station name or station code.",locationError:"We could not access your location. Allow location access and try again.",crowd:"Live crowd level",low:"Low crowd",moderate:"Moderate crowd",high:"High crowd",unavailable:"Crowd data unavailable",selected:"Selected station",normal:"All MRT and LRT services are operating normally",disruption:"Some train services are affected",normalHelp:"There are currently no train service disruptions reported by LTA.",affected:"Affected lines",direction:"Direction",stations:"Affected stations",publicBus:"Free public bus",shuttle:"Free MRT shuttle",announcements:"Passenger advisories",lines:"Line status",operating:"Operating normally",affectedBadge:"Service affected",refreshing:"Loading live status from LTA",error:"Unable to load live train status",refresh:"Refresh",updated:"Updated",lineHelp:"Tap a line to see every station",loadingLine:"Loading stations…",mapTitle:"Singapore MRT system map",mapHelp:"Preview the official MRT and LRT map. Zoom or pan to inspect it clearly.",previewMap:"Preview Singapore MRT map",openMap:"Open official high-resolution map",close:"Close",note:"Data from Singapore LTA DataMall and refreshed every 30 seconds. LTA does not provide routine per-train arrival countdowns during normal service."}
} as const;

const MrtStatus=()=>{
const [language,setLanguage]=useState<Language>(()=>localStorage.getItem("bus-status-language")==="en"?"en":"zh");
const [data,setData]=useState<StatusData|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
const [query,setQuery]=useState(""),[stations,setStations]=useState<Station[]>([]),[selected,setSelected]=useState<Station|null>(null),[crowd,setCrowd]=useState<Crowd[]>([]),[stationMessage,setStationMessage]=useState(""),[searching,setSearching]=useState(false);const t=copy[language];
const [selectedLine,setSelectedLine]=useState<string|null>(null),[lineStations,setLineStations]=useState<Station[]>([]);
const load=useCallback(async(quiet=false)=>{if(!quiet)setLoading(true);try{const r=await fetch("/api/train-status",{cache:"no-store"}),v=await r.json() as StatusData&{error?:string};if(!r.ok)throw new Error(v.error||t.error);setData(v);setError("");}catch(e){setError(e instanceof Error?e.message:t.error);}finally{setLoading(false);}},[t.error]);
useEffect(()=>{void load();},[load]);useEffect(()=>{const timer=window.setInterval(()=>void load(true),30000);return()=>clearInterval(timer);},[load]);
const switchLanguage=(next:Language)=>{setLanguage(next);localStorage.setItem("bus-status-language",next);};
const stationName=(station:Station,codes=station.codes)=>language==="zh"?(codes.map(code=>stationNameMap[code]).find(Boolean)||station.name.replace(/\s+(MRT|LRT)\s+STATION.*$/i,"")):station.name.replace(/\s+(MRT|LRT)\s+STATION.*$/i,"");
const distance=(a:number,b:number,c:number,d:number)=>{const rad=(v:number)=>v*Math.PI/180,x=rad(c-a),y=rad(d-b),h=Math.sin(x/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(y/2)**2;return Math.round(6371000*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h)));};
const chooseStation=async(s:Station)=>{setSelected(s);setStations([]);setQuery(s.name);setCrowd([]);if(!s.codes.length)return;try{const r=await fetch(`/api/station-crowd?codes=${encodeURIComponent(s.codes.join(","))}`),v=await r.json() as {levels?:Crowd[]};setCrowd(v.levels||[]);}catch{setCrowd([]);}};
const searchStations=async(e:FormEvent)=>{e.preventDefault();if(query.trim().length<2)return;setSearching(true);setStationMessage("");setSelected(null);try{const r=await fetch(`/api/mrt-stations?q=${encodeURIComponent(query.trim())}`),v=await r.json() as {stations?:Station[]};const found=v.stations||[];setStations(found);if(!found.length)setStationMessage(t.noStation);}catch{setStationMessage(t.noStation);}finally{setSearching(false);}};
const useLocation=()=>{if(!navigator.geolocation){setStationMessage(t.locationError);return;}setSearching(true);setStationMessage("");navigator.geolocation.getCurrentPosition(async({coords})=>{try{const r=await fetch("/api/mrt-stations"),v=await r.json() as {stations?:Station[]};const nearest=(v.stations||[]).map(s=>({...s,distance:distance(coords.latitude,coords.longitude,s.lat,s.lng)})).sort((a,b)=>(a.distance||0)-(b.distance||0)).slice(0,5);setStations(nearest);if(!nearest.length)setStationMessage(t.noStation);}catch{setStationMessage(t.noStation);}finally{setSearching(false);}},()=>{setStationMessage(t.locationError);setSearching(false);},{enableHighAccuracy:true,timeout:12000,maximumAge:60000});};
const stationOrder=(station:Station,prefixes:string[])=>{const codes=station.codes.filter(code=>prefixes.some(prefix=>isLineCode(code,prefix)));const code=codes[0]||"ZZ999";const prefixIndex=Math.max(0,prefixes.findIndex(prefix=>isLineCode(code,prefix)));const number=Number(code.match(/\d+/)?.[0]||999);return prefixIndex*1000+number;};
const openLine=(code:string)=>{if(selectedLine===code){setSelectedLine(null);setLineStations([]);return;}const prefixes=linePrefixes[code]||[];const builtInStations=officialStationList.filter(station=>prefixes.some(prefix=>isLineCode(station.code,prefix))).map(station=>({name:station.en,address:"",codes:[station.code],lat:0,lng:0})).sort((a,b)=>stationOrder(a,prefixes)-stationOrder(b,prefixes));setLineStations(builtInStations);setSelectedLine(code);};
const crowdText=crowd.some(i=>i.level?.toLowerCase()==="h")?t.high:crowd.some(i=>i.level?.toLowerCase()==="m")?t.moderate:crowd.some(i=>i.level?.toLowerCase()==="l")?t.low:t.unavailable;
const affectedCodes=new Set((data?.affectedSegments||[]).map(i=>["CEL","CGL"].includes(i.Line||"")?"CCL":["SEL","SWL"].includes(i.Line||"")?"SKL":["PEL","PWL"].includes(i.Line||"")?"PGL":i.Line));
const lineDetails=(code:string)=><div className="overflow-hidden rounded-[24px] border bg-white shadow-sm sm:col-span-2"><div className="flex items-center gap-3 border-b px-5 py-4"><span className="h-3 w-3 rounded-full" style={{backgroundColor:lineColours[code]}}/><div><h3 className="font-black">{language==="zh"?lines.find(line=>line[0]===code)?.[1]:lines.find(line=>line[0]===code)?.[2]}</h3><p className="text-xs text-slate-500">{lineStations.length} {language==="zh"?"个车站":"stations"}</p></div></div><div className="space-y-6 px-5 py-6">{branchesFor(code).map((branch,branchIndex)=>{const branchStations=lineStations.filter(station=>station.codes.some(stationCode=>stationCode===branch.anchor||branch.prefixes.some(prefix=>isLineCode(stationCode,prefix)))).sort((a,b)=>{const anchorA=a.codes.includes(branch.anchor||"")?-1:0,anchorB=b.codes.includes(branch.anchor||"")?-1:0;return anchorA-anchorB||stationOrder(a,branch.prefixes)-stationOrder(b,branch.prefixes);});return <div key={`${code}-${branchIndex}`}><div className="mb-3 flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full" style={{backgroundColor:lineColours[code]}}/><h4 className="text-sm font-black">{language==="zh"?branch.zh:branch.en}</h4></div><div className="overflow-x-auto pb-2"><div className="flex min-w-max items-start">{branchStations.map((station,index)=>{const codes=station.codes.filter(stationCode=>stationCode===branch.anchor||branch.prefixes.some(prefix=>isLineCode(stationCode,prefix)));return <div key={`${code}-${branchIndex}-${station.name}-${index}`} className="relative w-32 shrink-0 px-2 text-center"><div className="absolute left-0 right-0 top-[9px] h-1" style={{backgroundColor:lineColours[code]}}/><span className="relative z-10 mx-auto block h-[22px] w-[22px] rounded-full border-4 bg-white" style={{borderColor:lineColours[code]}}/><p className="mt-2 text-xs font-black">{codes.join(" · ")}</p><p className="mt-1 text-xs leading-4 text-slate-600">{stationName(station,codes)}</p></div>})}</div></div></div>})}</div></div>;
const title=language==="zh"?"新加坡地铁站查询｜附近MRT、实时拥挤度与运行状态｜忠邦华语演讲会":"Singapore MRT Station, Crowd & Service Status | Chong Pang TMC",description=language==="zh"?"查找附近的新加坡地铁站，搜索MRT/LRT站名或编号，并查看实时拥挤度、路线运行状态与服务公告。":"Find nearby Singapore MRT/LRT stations and check live crowd levels, line status and advisories.";
return <main className="min-h-screen bg-[#f2f6ed] font-body text-[#092623]"><Helmet><html lang={language==="zh"?"zh-CN":"en"}/><title>{title}</title><meta name="description" content={description}/><link rel="canonical" href="https://chongpangtmc.hellosg.org/mrt_status"/></Helmet>
<header className="bg-[#092f2b] text-white"><div className="mx-auto flex max-w-3xl items-center justify-between gap-3 px-5 py-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-red-600"><TrainFront size={22}/></span><div><p className="text-base font-black sm:text-xl">{language==="zh"?<><span>忠邦华语演讲会</span><span className="ml-1.5 text-red-400">温馨服务</span></>:t.brand}</p><a href="https://chongpangtmc.hellosg.org/" target="_blank" rel="noopener noreferrer" className="text-[10px] font-bold text-white/80 underline decoration-red-500 decoration-2 underline-offset-4 sm:text-xs">chongpangtmc.hellosg.org</a></div></div><div className="flex rounded-full bg-white/10 p-1 text-xs font-bold"><button onClick={()=>switchLanguage("zh")} className={`rounded-full px-2.5 py-1 ${language==="zh"?"bg-white text-[#092f2b]":"text-emerald-100"}`}>中文</button><button onClick={()=>switchLanguage("en")} className={`rounded-full px-2.5 py-1 ${language==="en"?"bg-white text-[#092f2b]":"text-emerald-100"}`}>EN</button></div></div></header>
<div className="mx-auto max-w-3xl px-4 pb-12 pt-5 sm:px-5"><nav className="mb-5 grid grid-cols-2 rounded-2xl bg-white p-1.5 shadow-sm"><Link to="/bus_status" className="rounded-xl px-4 py-2.5 text-center text-sm font-bold text-slate-500">{t.bus}</Link><span className="rounded-xl bg-[#092f2b] px-4 py-2.5 text-center text-sm font-bold text-white">{t.mrt}</span></nav>
<section className="rounded-[28px] bg-[#092f2b] p-6 text-white shadow-xl sm:p-8"><p className="text-xs font-bold tracking-[.14em] text-lime-300">MRT · LRT</p><h1 className="mt-2 text-3xl font-black tracking-[-.04em] sm:text-4xl">{t.heading}</h1><p className="mt-2 text-sm text-emerald-100">{t.intro}</p>
<form onSubmit={searchStations} className="mt-6 flex gap-2"><div className="relative min-w-0 flex-1"><Search className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" size={19}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search} className="h-12 rounded-2xl border-0 bg-white pl-11 text-base font-semibold text-slate-950"/></div><Button disabled={searching} className="h-12 rounded-2xl bg-[#c9f45b] px-5 font-bold text-[#092f2b] hover:bg-lime-300">{t.go}</Button></form><p className="mt-2 text-xs text-emerald-100">{t.example}</p><button type="button" onClick={useLocation} disabled={searching} className="mt-4 flex items-center gap-2 text-sm font-semibold text-emerald-100"><LocateFixed size={17} className={searching?"animate-pulse":""}/>{searching?t.locating:t.location}</button>
{stationMessage&&<p className="mt-3 rounded-xl bg-amber-100 px-3 py-2 text-xs text-amber-950">{stationMessage}</p>}{!!stations.length&&<div className="mt-4 overflow-hidden rounded-2xl bg-white text-[#092623]"><p className="border-b px-4 py-3 text-sm font-bold">{stations.some(s=>s.distance!==undefined)?t.nearest:t.results}</p>{stations.map((s,i)=><button key={`${s.name}-${i}`} type="button" onClick={()=>void chooseStation(s)} className="flex w-full items-center justify-between gap-3 border-b px-4 py-3 text-left last:border-0 hover:bg-emerald-50"><span><strong className="text-sm">{stationName(s)}</strong><span className="mt-0.5 block text-xs text-slate-500">{s.codes.join(" · ")||s.address}</span></span>{s.distance!==undefined&&<span className="shrink-0 rounded-full bg-[#e8f8bd] px-2.5 py-1 text-xs font-bold">{s.distance} {t.metres}</span>}</button>)}</div>}
{selected&&<div className="mt-4 rounded-2xl bg-white p-4 text-[#092623]"><p className="text-xs font-bold text-emerald-700">{t.selected}</p><h2 className="mt-1 text-xl font-black">{stationName(selected)}</h2><p className="mt-1 text-sm text-slate-500">{selected.codes.join(" · ")} {selected.address&&`· ${selected.address}`}</p><div className="mt-3 rounded-xl bg-emerald-50 px-3 py-2"><span className="text-xs font-bold text-emerald-700">{t.crowd}</span><strong className="ml-2 text-sm">{crowdText}</strong></div></div>}
<div className={`mt-5 rounded-2xl p-5 ${error?"bg-amber-100 text-amber-950":data?.normal?"bg-[#c9f45b] text-[#092f2b]":"bg-red-100 text-red-950"}`}><div className="flex gap-3">{error||!data?.normal?<AlertTriangle/>:<CheckCircle2/>}<div><h2 className="text-lg font-black">{loading&&!data?t.refreshing:error||(data?.normal?t.normal:t.disruption)}</h2>{!error&&data?.normal&&<p className="mt-1 text-sm font-medium opacity-80">{t.normalHelp}</p>}</div></div></div></section>
{!!data?.affectedSegments.length&&<section className="mt-6"><h2 className="text-xl font-black">{t.affected}</h2><div className="mt-3 space-y-3">{data.affectedSegments.map((i,n)=><article key={n} className="rounded-2xl border border-red-200 bg-white p-5"><strong className="text-red-700">{i.Line||"MRT"} · {t.affectedBadge}</strong><p className="mt-2 text-sm">{i.Direction&&`${t.direction}: ${i.Direction} · `}{i.Stations&&`${t.stations}: ${i.Stations}`}</p>{i.FreePublicBus&&<p className="mt-2 text-sm">{t.publicBus}: {i.FreePublicBus}</p>}{i.FreeMRTShuttle&&<p className="mt-2 text-sm">{t.shuttle}: {i.FreeMRTShuttle}</p>}</article>)}</div></section>}
<a href={`/transit/singapore-mrt-system-map-${language}.webp`} target="_blank" rel="noopener noreferrer" className="mt-7 flex w-full items-center justify-center gap-2 rounded-2xl bg-[#092f2b] px-5 py-3.5 text-sm font-bold text-white shadow-sm hover:bg-[#12443e]"><Map size={18}/>{t.previewMap}<ExternalLink size={15}/></a>
<p className="mt-2 text-center text-[11px] text-slate-500">{language==="zh"?"高清压缩图由 Cloudflare 加速 · ":"Optimized map delivered by Cloudflare · "}<a href={officialMapUrls[language]} target="_blank" rel="noopener noreferrer" className="font-bold text-emerald-800 underline underline-offset-2">{t.openMap}</a></p>
<section className="mt-7"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">{t.lines}</h2><p className="mt-1 text-xs text-slate-500">{t.lineHelp}</p></div><button onClick={()=>void load()} className="flex items-center gap-1.5 rounded-full bg-white px-3 py-2 text-xs font-bold"><RefreshCw size={14} className={loading?"animate-spin":""}/>{t.refresh}</button></div><div className="mt-3 grid gap-3 sm:grid-cols-2">{lines.map(([code,zh,en,colour])=>{const affected=affectedCodes.has(code),active=selectedLine===code;return <div key={code} className="contents"><button type="button" onClick={()=>openLine(code)} aria-expanded={active} className={`flex items-center gap-3 rounded-2xl border bg-white p-4 text-left transition ${active?"border-[#092f2b] ring-2 ring-[#092f2b]/10":"hover:border-emerald-300"}`}><span className={`grid h-11 w-11 place-items-center rounded-xl text-xs font-black text-white ${colour}`}>{code}</span><div className="min-w-0 flex-1"><h3 className="font-bold">{language==="zh"?zh:en}</h3><p className={`text-xs font-semibold ${affected?"text-red-600":"text-emerald-700"}`}>{affected?t.affectedBadge:t.operating}</p></div><span className={`text-lg transition ${active?"rotate-90":""}`}>›</span></button>{active&&lineDetails(code)}</div>})}</div>
 </section>
{!!data?.messages.length&&<section className="mt-7 rounded-2xl bg-amber-50 p-5"><h2 className="font-black text-amber-950">{t.announcements}</h2>{data.messages.map((m,i)=><p key={i} className="mt-3 text-sm leading-6 text-amber-900">{m}</p>)}</section>}
<p className="mt-6 text-center text-xs leading-6 text-slate-500"><Clock3 className="mr-1 inline" size={13}/>{data?.updatedAt?`${t.updated} ${new Date(data.updatedAt).toLocaleTimeString(language==="zh"?"zh-SG":"en-SG")} · `:""}{t.note}</p></div></main>;
};
export default MrtStatus;
